/*
  ptnio - Portable TCP Network IO
  Copyright (C) 2017-2018 Teddy ASTIE

  Permission to use, copy, modify, and/or distribute this software for any
  purpose with or without fee is hereby granted, provided that the above
  copyright notice and this permission notice appear in all copies.

  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

#ifndef H_CMD_CODES
#define H_CMD_CODES

#define CMD_SUCCESS         0
#define CMD_INVALID_ARGS    1
#define CMD_OUT_OF_MEMORY   2
#define CMD_NETWORK_ERROR   3
#define CMD_NOT_FOUND       4
#define CMD_OVERWRITTEN     5
#define CMD_INTERNAL_ERROR  6
#define CMD_BIND_ERROR      7
#define CMD_INVALID_HOST    8
#define CMD_DATA_AVAILABLE  9
#define CMD_CLIENT_OOM     10
#define CMD_NMS_ZERO_SIZE  11
#define CMD_IPC_ERROR      12

#endif /* H_CMD_CODES */
